export const SUPABASE_URL = "https://lulexleknwwmceddccxx.supabase.co";
export const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1bGV4bGVrbnd3bWNlZGRjY3h4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA3NTk4MDMsImV4cCI6MjA3NjMzNTgwM30.P0dZ2_CasW99l1RfmUwPJmalLWw1frxhPM9xCYBl7ho";
